
#If school-edition is true in the values.yaml file, then the following helm file will be installed
  
  {{- if .Values.school-edition }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: school-edition-applications-{{ .Values.environment }}
  namespace: {{ .Values.argocd.namespace }}
spec:
  generators:
    - git:
        repoURL: '{{ .Values.argocd.configRepoUrl }}'
        revision: HEAD
        directories:
          - path: 'school-edition/overlay/{{ .Values.environment }}/*'
  template:
    metadata:
      name: '{{path.basename}}-dns'
    spec:
      project: campuszeus-{{ .Values.environment }}
      source:
        repoURL: '{{ .Values.argocd.configRepoUrl }}'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: dns-{{path.basename}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  
  {{- end }}