apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
spec:
  source:
    helm:
      values: |
        image:
          repository: bitnami/postgresql
          tag: "11.11.0-debian-10-r0"
        postgresqlUsername: postgres
        postgresqlPassword: postgres
        postgresqlDatabase: postgres
