apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - observability-namespace.yaml
  - kube-prometheus-stack/helm-release.yaml
  - grafana/helm-release.yaml
  - loki/helm-release.yaml
  - promtail/helm-release.yaml
