apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  project: k8s-app-factory-project-nonprod
  source:
    helm:
      values: | 
        ingress:
          enabled: false