apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  project: k8s-app-factory-project-nonprod
  source:
    helm:
      values: | 
        ingress:
          enabled: true
          hosts:
            - grafana-nonprod.yaal.be
          ingressClassName: nginx
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            external-dns.alpha.kubernetes.io/access: "public"
            external-dns.alpha.kubernetes.io/hostname: "grafana-nonprod.yaal.be"
          tls:
            - hosts:
                - grafana-nonprod.yaal.be
              secretName: cloudflare-origin-ca-cert