apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-management-nonprod
  namespace: argo
spec:
  project: k8s-app-factory-project-nonprod
  source:
    repoURL: https://github.com/speelyaal/campuszeus.config.git
    targetRevision: HEAD
    path: argocd-management/overlays/nonprod
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true