apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-{{ .Values.cluster}}
  namespace: argo
spec:
  project: {{ .Values.argoProjectPrefix }}-{{ .Values.cluster }}
  source:
    repoURL: https://github.com/speelyaal/campuszeus.config.git
    targetRevision: HEAD
    path: keycloak/overlays/{{ .Values.cluster }}
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true