apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argo
spec:
  project: k8s-app-factory-project-nonprod
  source:
    repoURL: "registry-1.docker.io/bitnamicharts"
    chart: external-dns
    targetRevision: 8.0.0
    helm:
      values: |
        image:
          repository: bitnami/external-dns
          tag: "0.14.2"
        provider: aws
        aws:
          zoneType: public
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true