image:
  repository: bitnami/external-dns
  tag: "0.15.0-debian-12-r5"
provider: aws
aws:
  credentials:
    secretName: external-dns-aws-credentials
    accessKey: AWS_ACCESS_KEY_ID
    secretKey: AWS_SECRET_ACCESS_KEY
  zoneType: public
domainFilters:
  - "example.com"
  - "example.org"
txtOwnerId: "external-dns"