apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/external-dns

patches:
  - target:
      kind: HelmChart
      name: external-dns
    patch: |-
      - op: replace
        path: /helmCharts/0/valuesInline/aws/zoneType
        value: private
      - op: replace
        path: /helmCharts/0/valuesInline/domainFilters
        value:
          - "nonprod.example.com"
      - op: replace
        path: /helmCharts/0/valuesInline/txtOwnerId
        value: "external-dns-nonprod"