apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  source:
    helm:
      values: |
        image:
          repository: bitnami/external-dns
          tag: "0.15.0"
        sources:
          - ingress
        provider: godaddy
        policy: sync
        extraArgs:
          source: ingress
          domain-filter: cz1.com
          txt-prefix: "cz"
          txt-owner-id: "external-dns"
          godaddy-api-key: "key"
          godaddy-api-secret: "secret"
        extraEnvVars:
          - name: DO_TOKEN
            value: "token"
        txtOwnerId: "external-dns"