apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  source:
    helm:
      values: |
        image:
          repository: bitnami/external-dns
          tag: "0.15.0"
        sources:
          - ingress
        provider: digitalocean
        policy: sync
        extraArgs:
          source: ingress        
          txt-prefix: "external-dns"
        extraEnvVars:
          - name: DO_TOKEN
            valueFrom:
              secretKeyRef:
                name: digitalocean-api-token
                key: DO_TOKEN
                namespace: external-dns
        txtOwnerId: "external-dns"
        domainFilters: 
          - "acurion.xyz"
          - "campuszeus.xyz"
          - "speelyaal.xyz"
