apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  project: k8s-app-factory-project-nonprod
  source:
    helm:
      values: |
        sources:
          - ingress
        provider: cloudflare
        policy: sync
        extraArgs:
          source: ingress        
          txt-prefix: "external-dns"
        extraEnvVars:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-token
                key: CF_API_TOKEN
                namespace: external-dns
          - name: CF_API_KEY
            valueFrom:
              secretKeyRef:
                name: cloudflare-api-key
                key: CF_API_KEY
                namespace: external-dns
          - name: CF_API_EMAIL
            value: "ashok@speelyaal.com"
        txtOwnerId: "external-dns"
        domainFilters: 
          - "acurion.xyz"
          - "campuszeus.xyz"
          - "yaal.be"
