apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argo
spec:
  project: project-name
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    chart: promtail
    targetRevision: 6.16.6
    helm:
      valuesFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true