apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/namespace.yaml
  - cert-manager/helm-release.yaml
  - external-dns/namespace.yaml
  - external-dns/helm-release.yaml
  - nginx-ingress-controller/namespace.yaml
  - nginx-ingress-controller/helm-release.yaml
