apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  - external-dns/namespace.yaml
  - external-dns/helm-release.yaml
  - nginx-ingress-controller/namespace.yaml
  - nginx-ingress-controller/helm-release.yaml
# As we use Cloudflare certificate manager, we do not need to install cert-manager as of now
# Uncomment the following lines if you want to install cert-manager and use letsencrypt
#  - cert-manager/namespace.yaml
#  - cert-manager/cert-manager.crds-1.16.2.yaml
#  - cert-manager/helm-release.yaml
#  - cert-manager/cert-cluster-issuer.yaml
#  - cert-manager/cert-cluster-staging-issuer.yaml
