apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
spec:
  source:
    helm:
      values: |
        controller:
          service:
            annotations:
              load-balancer.hetzner.cloud/name : k8s-ingress-lb-nbg1
              load-balancer.hetzner.cloud/location: "nbg1" 
              load-balancer.hetzner.cloud/type: "lb11"
