apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
spec:
  source:
    helm:
      values: |
        controller:
          service:
            annotations:
              load-balancer.hetzner.cloud/name : k8s-ingress-lb-hel1
              load-balancer.hetzner.cloud/location: "hel1" 
              load-balancer.hetzner.cloud/use-private-ip: "false"
