apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  source:
    helm:
      values: |
        provider: aws
        aws:
          credentials:
            secretName: dev-external-dns-aws-credentials
          zoneType: private
        domainFilters:
          - "dev.example.com"
        txtOwnerId: "external-dns-dev"