apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: observability
spec:
  project: project-name
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    chart: grafana
    targetRevision: 8.8.2
    helm:
      valuesFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true