environment: nonprod
cluster: nonprod
argocd:
    namespace: argo
    configRepoUrl: https://github.com/speelyaal/campuszeus.config.git
dnsManagement:
    enabled: true
    namespace: dns-management-nonprod
observability:
    enabled: true
    namespace: observability-nonprod