apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  source:
    helm:
      values: |
        service:
          type: LoadBalancer
        ingress:
          enabled: true
          hostname: dev-nginx.example.com
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"