
#If identity-and-access is true in the values.yaml file, then the following helm file will be installed
  
  {{- if .Values.identityAndAccess }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: identity-and-access-applications-{{ .Values.environment }}
  namespace: {{ .Values.argocd.namespace }}
spec:
  generators:
    - git:
        repoURL: '{{ .Values.argocd.configRepoUrl }}'
        revision: HEAD
        directories:
          - path: 'identity-and-access/overlays/{{ .Values.environment }}/*'
  template:
    metadata:
      name: '{{path.basename}}-dns'
    spec:
      project: campuszeus-{{ .Values.environment }}
      source:
        repoURL: '{{ .Values.argocd.configRepoUrl }}'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: dns-{{path.basename}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  
  {{- end }}