apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-distributed
  namespace: argo
spec:
  project: project-name
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    chart: loki-distributed
    targetRevision: 0.80.0
    helm:
      valuesFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true