apiVersion: v1
kind: Secret
metadata:
  name: campuszeus-config-repo
  namespace: argo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: "https://github.com/speelyaal/campuszeus.config.git"
  type: "git"
  project: "k8s-app-factory-project-{{ .Values.environment }}"