apiVersion: v1
kind: Secret
metadata:
  name: campuszeus-config-repo
  namespace: argo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: "https://github.com/speelyaal/campuszeus.config.git"
  name: "campuszeus.config"
  type: "git"
  project: "{{.Values.argoProjectName}}"