apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: grafana-repo
  namespace: argo
stringData:
  url: "https://grafana.github.io/helm-charts"
  name: "grafana"
  type: "helm"
  project: "{{.Values.argoProjectName}}"