apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: ingress-nginx-repo
  namespace: argo
stringData:
  url: "https://kubernetes.github.io/ingress-nginx"
  name: "ingress-nginx"
  type: "helm"
  project: "k8s-app-factory-project-{{ .Values.environment }}"