apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: jetstack-cert-manager-repo
  namespace: argo
stringData:
  url: "https://charts.jetstack.io"
  name: "jetstack"
  type: "helm"
  project: "k8s-app-factory-project-{{ .Values.environment }}"