apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: prometheus-community-repo
  namespace: argo
stringData:
  url: "https://prometheus-community.github.io/helm-charts"
  name: "prometheus-community"
  type: "helm"
  project: "{{.Values.argoProjectName}}"